# Generated by Django 5.2.8 on 2025-11-22 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Watchlist',
                'verbose_name_plural': 'Watchlists',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, verbose_name='Ticker')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='core.watchlist', verbose_name='Watchlist')),
            ],
            options={
                'verbose_name': 'Action dans watchlist',
                'verbose_name_plural': 'Actions dans watchlist',
                'ordering': ['ticker'],
                'unique_together': {('watchlist', 'ticker')},
            },
        ),
    ]
