# Generated by Django 5.2.8 on 2025-11-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='color',
            field=models.CharField(choices=[('#dc3545', 'Rouge'), ('#fd7e14', 'Orange'), ('#ffc107', 'Jaune'), ('#28a745', 'Vert'), ('#20c997', 'Turquoise'), ('#17a2b8', 'Cyan'), ('#007bff', 'Bleu'), ('#6610f2', 'Violet'), ('#e83e8c', 'Rose'), ('#6c757d', 'Gris')], default='#007bff', max_length=7, verbose_name='Couleur'),
        ),
    ]
