# Generated by Django 5.2.8 on 2025-12-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_watchlist_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, verbose_name='Ticker')),
                ('account_id', models.CharField(max_length=50, verbose_name='Compte IB')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'entrée")),
                ('entry_date', models.DateTimeField(verbose_name="Date d'entrée")),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de sortie')),
                ('exit_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de sortie')),
                ('sl_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Stop Loss')),
                ('tp_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Take Profit')),
                ('pnl_dollar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='P&L ($)')),
                ('pnl_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='P&L (%)')),
                ('risk_reward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Risk/Reward (R)')),
                ('exit_type', models.CharField(blank=True, choices=[('TP', 'Take Profit'), ('SL', 'Stop Loss'), ('MANUAL', 'Manuel')], max_length=10, null=True, verbose_name='Type de sortie')),
                ('ib_order_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID ordre IB')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'ordering': ['-entry_date'],
            },
        ),
    ]
