# Generated by Django 5.2.8 on 2025-12-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=50, unique=True, verbose_name='Compte IB')),
                ('base_risk_percent', models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='Risque de base (%)')),
                ('advance_level_1_min', models.IntegerField(default=7, verbose_name='Niveau AVANCE 1 min')),
                ('advance_level_2_min', models.IntegerField(default=14, verbose_name='Niveau AVANCE 2 min')),
                ('advance_level_3_min', models.IntegerField(default=21, verbose_name='Niveau AVANCE 3 min')),
                ('drawdown_level_1_max', models.IntegerField(default=-5, verbose_name='Niveau DRAWDOWN 1 max')),
                ('drawdown_level_2_max', models.IntegerField(default=-10, verbose_name='Niveau DRAWDOWN 2 max')),
                ('drawdown_level_3_max', models.IntegerField(default=-15, verbose_name='Niveau DRAWDOWN 3 max')),
                ('drawdown_level_4_max', models.IntegerField(default=-20, verbose_name='Niveau DRAWDOWN 4 max')),
                ('current_consecutive_counter', models.IntegerField(default=0, verbose_name='Compteur actuel')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Profil de Risque',
                'verbose_name_plural': 'Profils de Risque',
            },
        ),
        migrations.AddField(
            model_name='trade',
            name='consecutive_counter_after',
            field=models.IntegerField(default=0, verbose_name='Compteur après ce trade'),
        ),
    ]
